name: dd_clo_packing_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler:
  google_fonts:
  get:
  share_plus:
  shared_preferences:
  url_launcher:
  connectivity_plus:
  package_info_plus:
  http:
  audioplayers:
  image_picker:
  mobile_scanner:
  webview_flutter: ^4.4.2
  syncfusion_flutter_pdfviewer: ^31.2.18  # Check for the latest version
  battery_plus:
  geolocator:
  intl:
  geocoding:
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/audio/
